version: 2
jobs:
  test: &test
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn config set cache-folder /tmp/yarn
      - run: yarn
      - run: yarn --cwd functions
      - run: yarn lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  deploy:
    <<: *test
    steps:
      - attach_workspace:
          at: ~/
      - run: echo $DOTENV | base64 --decode > .env
      - run: npm run build && npm run deploy --silent -- --token $FIREBASE_TOKEN

workflows:
  version: 2
  default:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test